name: build-image
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: useless-app
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: uselessregistry.azurecr.io
          # Username used to log against the Docker registry
          username: ${{ secrets.AZURE_USER_NAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.AZURE_PUSH_KEY }}
      - name: Build Container
        uses: actions/checkout@main
      - run: docker build -t uselessregistry.azurecr.io/$REPO_NAME:latest .
      - run: docker push uselessregistry.azurecr.io/$REPO_NAME:latest
